services:
  firefox:
    image: selenium/standalone-firefox:128.0-20250717
    shm_size: 2gb
    ports:
      - "4444:4444"
      - "7900:7900"

  app:
    build:
      context: .
    environment:
      SPRING_PROFILES_ACTIVE: hsql
      SPRING_DATASOURCE_URL: jdbc:hsqldb:file:/app/miner-db/miner_schedule