services:
  db:
    container_name: miner-schedule-db
    image: postgres:17.2
    restart: always
    # set shared memory limit when using docker-compose
    shm_size: 128mb
    environment:
      POSTGRES_USER: miner_schedule
      POSTGRES_PASSWORD: ${PG_PASSWORD}
    volumes:
      - ${PG_DATA_HOST_PATH}:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  app:
    build:
      context: .
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/miner_schedule