spring:
  main:
    banner-mode: off
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: org.postgresql.Driver
    username: miner_schedule
    password: 1
    url: jdbc:postgresql://localhost:5432/miner_schedule
  sql:
    init:
      mode: always
  quartz:
    jdbc:
      initialize-schema: ${app.scheduler.jobStore.schema-init}
    job-store-type: jdbc
    properties:
      # docs: https://github.com/quartz-scheduler/quartz/blob/main/docs/configuration.adoc
      org:
        quartz:
          scheduler:
            instanceId: AUTO
          jobStore:
            driverDelegateClass: org.quartz.impl.jdbcjobstore.${app.scheduler.jobStore.driverDelegate} #Указываем диалект для запросов к БД
            useProperties: true #Указываем, что все данные в БД будут храниться в качестве строк, а не в двоичном формате
          threadPool: #Указываем настройки для создания пула поток, на котором будут выполняться джобы
            class: org.quartz.simpl.SimpleThreadPool
            threadCount: 2
            threadsInheritContextClassLoaderOfInitializingThread: true
        auto-startup: ${app.scheduler.auto-start:true}



logging:
  level:
    root: INFO
    org.quartz: INFO
    jdbc: OFF
    org.openqa.selenium.devtools: ERROR

selenium:
  driver:
    remote: http://localhost:4444